# Generated by Django 5.2.6 on 2025-09-17 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('nacionalidad', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('genero', models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('hiphop', 'Hip-Hop'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musica', to='musica.artista')),
            ],
        ),
    ]
